# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHG2HAOUIUqsJSMrNLcgH92PG-EKNTRL
"""

import streamlit as st
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# Page Configuration
# -------------------------------
st.set_page_config(page_title="Smart Fertilizer AI", layout="centered")

st.title("🌱 Smart Fertilizer & Crop Recommendation System")

st.write("Enter soil parameters to get AI-based crop and fertilizer suggestions.")

# -------------------------------
# Load Model (Optimized)
# -------------------------------
@st.cache_resource
def load_model():
    return pickle.load(open("model.pkl","rb"))

model = load_model()

# -------------------------------
# Sidebar Info
# -------------------------------
st.sidebar.title("About")
st.sidebar.write("This app uses Machine Learning to recommend crops based on soil conditions.")

# -------------------------------
# Input Section
# -------------------------------
st.header("Soil Parameters Input")

col1, col2 = st.columns(2)

with col1:
    N = st.number_input("Nitrogen (N)", 0, 140)
    P = st.number_input("Phosphorus (P)", 0, 140)
    K = st.number_input("Potassium (K)", 0, 200)

with col2:
    temp = st.number_input("Temperature (°C)", 0.0, 50.0)
    humidity = st.number_input("Humidity (%)", 0.0, 100.0)
    ph = st.number_input("pH", 0.0, 14.0)
    rainfall = st.number_input("Rainfall (mm)", 0.0, 300.0)

# -------------------------------
# Prediction
# -------------------------------
if st.button("Predict Crop"):
    data = np.array([[N,P,K,temp,humidity,ph,rainfall]])
    result = model.predict(data)

    st.success(f"🌾 Recommended Crop: {result[0]}")

    # -------------------------------
    # Fertilizer Suggestions
    # -------------------------------
    st.subheader("Fertilizer Suggestions")

    if N < 40:
        st.warning("Low Nitrogen → Add Nitrogen fertilizer")
    elif N > 100:
        st.warning("High Nitrogen → Reduce fertilizer usage")

    if P < 30:
        st.warning("Low Phosphorus → Add Phosphate fertilizer")

    if K < 30:
        st.warning("Low Potassium → Add Potash fertilizer")

    if ph < 6:
        st.warning("Soil is acidic → Add lime")
    elif ph > 7.5:
        st.warning("Soil is alkaline → Add organic matter")

# -------------------------------
# Optional Dataset Visualization
# -------------------------------
st.header("Dataset Insights (Optional)")

try:
    data = pd.read_csv("Crop_cleaned.csv")

    if st.checkbox("Show Dataset"):
        st.write(data.head())

    if st.checkbox("Show pH Distribution"):
        fig, ax = plt.subplots()
        ax.hist(data['ph'])
        ax.set_title("pH Distribution")
        st.pyplot(fig)

except:
    st.info("Dataset not uploaded. Skipping visualization.")